name: Export OpenAI Secrets
description: Sets OPENAI_API_KEY and OPENAI_BASE_URL as environment variables for subsequent steps in the job when executed in a trusted context.
inputs: {}
runs:
  using: "composite"
  steps:
    - name: Export secrets to GITHUB_ENV
      shell: bash
      run: |
        # Only write if secrets exist. Composite action invoked from workflow will be run in the job's context.
        if [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        fi
        if [ -n "${{ secrets.OPENAI_BASE_URL }}" ]; then
          echo "OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }}" >> $GITHUB_ENV
        fi
