name: Bot Self-Work

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  selfwork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install pytest python-dotenv pyyaml orjson openai

      - name: Prepare folders
        run: |
          mkdir -p OPS/drafts OPS/logs OPS/reports PREVIEWS

      # ci_selfwork.py MUSS diese Outputs setzen:
      #   draft_path, preview_path, critic_level, ts, adds, rems
      - name: Create draft (CI headless)
        id: ci
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          SPEC_PATH: prompts/specs/hello_self.json
          TARGET: generated_module.py
        run: python scripts/ci_selfwork.py

      - name: What-If (no write)
        run: python apply_draft.py --draft "${{ steps.ci.outputs.draft_path }}" --whatif

      - name: Approve & write (only when labeled and Green)
        if: >
          github.event_name == 'pull_request' &&
          contains(toJson(github.event.pull_request.labels), '"name":"bot-apply"') &&
          steps.ci.outputs.critic_level == 'Green' &&
          github.event.pull_request.head.repo.full_name == github.repository
        run: |
          python apply_draft.py --draft "${{ steps.ci.outputs.draft_path }}" --approve
          echo "Wrote files."

      - name: Run smoke tests
        run: python -m pytest -q

      - name: Commit & push (only if we wrote)
        if: >
          github.event_name == 'pull_request' &&
          contains(toJson(github.event.pull_request.labels), '"name":"bot-apply"') &&
          steps.ci.outputs.critic_level == 'Green' &&
          github.event.pull_request.head.repo.full_name == github.repository
        run: |
          git config user.name  "bot-selfwork"
          git config user.email "bot@users.noreply.github.com"
          if ! git diff --quiet; then
            git add -A
            git commit -m "bot(selfwork): apply draft ${GITHUB_RUN_ID} [auto]"
            git push
          fi

      - name: Summarize
        run: |
          echo "Draft:   ${{ steps.ci.outputs.draft_path }}"
          echo "Preview: ${{ steps.ci.outputs.preview_path }}"
          echo "Critic:  ${{ steps.ci.outputs.critic_level }}"
